-- 코드를 입력하세요
/**
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, sum(AMOUNT*PRICE) TOTAL_SALES
from FOOD_PRODUCT a
inner join FOOD_ORDER b on a.PRODUCT_ID=b.PRODUCT_ID
where PRODUCE_DATE >= '2022-05-01' and  PRODUCE_DATE < '2022-06-01'
group by a.PRODUCT_ID, a.PRODUCT_NAME
order by TOTAL_SALES desc, a.PRODUCT_ID
**/
select O.PRODUCT_ID, PRODUCT_NAME, sum(AMOUNT*PRICE) TOTAL_SALES
from FOOD_ORDER O 
inner join FOOD_PRODUCT P on O.PRODUCT_ID=P.PRODUCT_ID
where date_format(PRODUCE_DATE,'%Y-%m') = '2022-05'
group by PRODUCT_ID, PRODUCT_NAME
order by TOTAL_SALES desc, PRODUCT_ID