-- 코드를 작성해주세요
SELECT YEAR, (M - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA AS A 
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS M
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)) AS T
ON YEAR(A.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR, YEAR_DEV

/**
with ai as
(select to_char(DIFFERENTIATION_DATE,'YYYY') year, max(SIZE_OF_COLONY)  yearmax
from ECOLI_DATA
group by to_char(DIFFERENTIATION_DATE,'YYYY')
)
select a.YEAR
        , yearmax - SIZE_OF_COLONY YEAR_DEV
        , ID
from ECOLI_DATA a left join ai b on to_char(a.DIFFERENTIATION_DATE,'YYYY')=b.year
order by a.year, YEAR_DEV
**/
